name: Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{ matrix.compiler }}
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-18", "clang-17", "gcc-14", "gcc-13", "gcc-12", "intel"]
        include:
          - cxx_flags: "-Wno-interference-size"
          - compiler: "clang-18"
            cxx_flags: ""
          - compiler: "clang-17"
            cxx_flags: ""
          - compiler: "intel"
            cxx_flags: "-fp-model=strict -Wno-overriding-option"
    container:
      image: ghcr.io/seqan/${{ matrix.compiler }}
      volumes:
        - /home/runner:/home/runner
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Load ccache
        uses: actions/cache@v4
        with:
          path: /home/runner/.ccache
          key: ccache-${{ runner.os }}-${{ github.workflow }}-${{ matrix.compiler }}-${{ github.ref }}

      - name: Configure tests
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_CXX_FLAGS="-Werror ${{ matrix.cxx_flags }}"
          make gtest_main

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k api_test cli_test display_layout measure_hyperloglog
          ccache -svvx

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure

