name: Unit Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: linux-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: true
      matrix:
        include:
          - name: "clang17"
            compiler: "clang-17"
            build: unit
            build_type: Release

          - name: "gcc13"
            compiler: "gcc-13"
            build_type: Release
            cxx_flags: -Wno-interference-size

          - name: "gcc12"
            compiler: "gcc-12"
            build_type: Release
            cxx_flags: -Wno-interference-size

          - name: "gcc11"
            compiler: "gcc-11"
            build_type: Release
            cxx_flags: -Wno-interference-size

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 125M

      - name: Install OpenMP
        if: contains(matrix.name, 'clang')
        run: install libomp-17-dev

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.18.6

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS="-Werror ${{ matrix.cxx_flags }}" \
                   -DCHOPPER_NATIVE_BUILD=OFF
          make -j2 gtest_build

      - name: Build tests
        run: |
          ccache -z
          cd build
          make -k -j2 api_test cli_test display_layout measure_hyperloglog
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j2 --output-on-failure

