name: macOS

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eeuxo pipefail {0}

jobs:
  build:
    name: ${{ matrix.compiler }}
    runs-on: macos-14
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        compiler: ["clang-18", "clang-17", "gcc-14", "gcc-13", "gcc-12"]
        include:
          - cxx_flags: "-Wno-interference-size"
          - compiler: "clang-18"
            cxx_flags: ""
          - compiler: "clang-17"
            cxx_flags: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 75M

      - name: Patch M1 GCC
        if: contains(matrix.compiler, 'gcc') && matrix.compiler != 'gcc-14'
        uses: seqan/actions/patch-m1-gcc@main
        with:
          compiler: ${{ matrix.compiler }}

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DCMAKE_CXX_FLAGS="-Werror ${{ matrix.cxx_flags }}"
          make gtest_main

      - name: Build tests
        working-directory: build
        run: |
          ccache -z
          make -k api_test cli_test display_layout measure_hyperloglog
          ccache -svvx

      - name: Run tests
        working-directory: build
        run: ctest . -j --output-on-failure
