name: Linux

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled

concurrency:
  group: misc-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -ex {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "Header clang17"
            compiler: "clang-17"
            build_type: Release
            cxx_flags: "-stdlib=libc++"

          - name: "Header gcc13"
            compiler: "gcc-13"
            build_type: Release
            cxx_flags: "-Wno-interference-size"

          - name: "Header gcc12"
            compiler: "gcc-12"
            build_type: Release
            cxx_flags: "-Wno-interference-size"

          - name: "Header gcc11"
            compiler: "gcc-11"
            build_type: Release
            cxx_flags: "-Wno-interference-size"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 75M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.25.3

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS="-Werror ${{ matrix.cxx_flags }}" \
                   -DCHOPPER_HEADER_TEST_ONLY=ON

      - name: Build tests
        env:
          CMAKE_BUILD_PARALLEL_LEVEL: 2
        run: |
          ccache -z || true
          cd build
          make -k test
          ccache -sv || true

      - name: Run tests
        run: |
          cd build
          ctest . -j2 --output-on-failure
