name: Unit macOS

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - unlabeled
  workflow_dispatch:

concurrency:
  group: macos-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name != 'push' }}

env:
  SHARG_NO_VERSION_CHECK: 1
  TZ: Europe/Berlin

defaults:
  run:
    shell: bash -Eexuo pipefail {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: macos-12
    timeout-minutes: 120
    if: github.repository_owner == 'seqan' || github.event_name == 'workflow_dispatch' || github.event.label.name == 'lint'
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "clang17"
            compiler: "clang-17"
            build_type: Release
            cxx_flags: "-stdlib=libc++" # For verbosity. This is already the default.

          - name: "gcc13"
            compiler: "gcc-13"
            build_type: Release
            cxx_flags: "-Wno-interference-size"

          - name: "gcc12"
            compiler: "gcc-12"
            build_type: Release
            cxx_flags: "-Wno-interference-size"

          - name: "gcc11"
            compiler: "gcc-11"
            build_type: Release
            cxx_flags: "-Wno-interference-size"

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Setup toolchain
        uses: seqan/actions/setup-toolchain@main
        with:
          compiler: ${{ matrix.compiler }}
          ccache_size: 125M

      - name: Install CMake
        uses: seqan/actions/setup-cmake@main
        with:
          cmake: 3.28.5

      - name: Configure tests
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
                   -DCMAKE_CXX_FLAGS="-Werror ${{ matrix.cxx_flags }}"
          make -j3 gtest_main

      - name: Debug
        if: failure()
        run: cat /Users/runner/work/chopper/chopper/build/CMakeFiles/CMakeError.log

      - name: Build tests
        run: |
          ccache -z
          cd build
          make -k -j3 api_test cli_test display_layout measure_hyperloglog
          ccache -sv

      - name: Run tests
        run: |
          cd build
          ctest . -j3 --output-on-failure
